name: Build

on: [workflow_call]

jobs:
  build-wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install tox
        run: python -m pip install --upgrade tox==4.23.2 tox-uv~=1.16.0

      - name: Build python app
        run: tox run -e build

      - name: Require non dirty git workspace
        run: |
          CHANGES=$(git status --porcelain)
          if [[ -n "$CHANGES" ]]; then
            echo "❌ Workspace is dirty. The following files have been modified:"
            echo "$CHANGES"
            exit 1
          else
            echo "✅ Workspace is clean."
          fi

      - name: Upload python artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  build-iso:
    name: Build ISO
    runs-on: ubuntu-latest
    env:
      COLUMNS: 160
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Install build dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libarchive-tools xorriso qemu-system-x86
          version: 1.0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install package
        run: pip install .

      - name: Build ISO
        run: voraus-debian-iso build

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: iso
          path: output/*.iso
