name: CI pipeline

permissions:
  contents: write
  id-token: write
  issues: write
  pages: write

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - "main"
    tags:
      - "*"

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  docs:
    uses: ./.github/workflows/docs.yml
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit
    needs:
      - build
  publish:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    needs:
      - test
      - lint
      - build
      - docs
