name: Publish

on: [workflow_call]

jobs:
  create-github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run JReleaser
        uses: jreleaser/release-action@v2
        with:
          version: latest
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_PROJECT_VERSION: ${{ github.ref_name }}

  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
          path: docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish-iso:
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: bypass-generic-public-production-cloud-local/voraus-debian-iso/
      JFROG_CLI_BUILD_NAME: voraus-debian-iso/${{ github.ref_name }}
      JFROG_CLI_BUILD_NUMBER: "1"
    steps:
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://voraus.jfrog.io
        with:
          oidc-provider-name: voraus-github-organization

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          name: iso
          path: output

      - name: Publish ISO
        run: |
          jf rt u "output/*.iso" "$DEPLOY_PATH"

      - name: Publish Build Info
        run: |
          jf rt build-publish
